network:
  version: 2
  renderer: networkd
  wifis:
    wlp2s0:  # Use 'wlp2s0' as per Wi-Fi interface name
      dhcp4: yes
      access-points:
        "DOT99 NET FIBER2HOME":
          password: "**********"

# Resreve static IP for the server config

network:
  version: 2
  renderer: networkd
  wifis:
    wlp2s0:
      access-points:
        "DOT99 NET FIBER2HOME":
          password: "**********"
      dhcp4: no
      addresses:
        - 192.168.1.***/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 0.0.0.0/0
          via: 192.168.*.*